if(NOT DEFINED KODI_DEPENDS_PREFIX_RESOLVED)
  message(FATAL_ERROR "KODI_DEPENDS_PREFIX_RESOLVED is required")
endif()

if(NOT DEFINED KODI_DEPENDS_HOST OR KODI_DEPENDS_HOST STREQUAL "")
  set(KODI_DEPENDS_HOST "x86_64-linux-gnu")
endif()

if(NOT DEFINED KODI_DEPENDS_RENDER_SYSTEM OR KODI_DEPENDS_RENDER_SYSTEM STREQUAL "")
  set(KODI_DEPENDS_RENDER_SYSTEM "gl")
endif()

set(_addon_deps_dir "${KODI_DEPENDS_PREFIX_RESOLVED}")
set(_lib_dir "${_addon_deps_dir}/lib")
set(_pkgconfig_dir "${_lib_dir}/pkgconfig")
set(_include_dir "${_addon_deps_dir}/include")

if(EXISTS "/usr/lib64")
  set(_host_libdir "/usr/lib64")
elseif(EXISTS "/usr/lib/${KODI_DEPENDS_HOST}")
  set(_host_libdir "/usr/lib/${KODI_DEPENDS_HOST}")
else()
  set(_host_libdir "/usr/lib")
endif()

function(_link_matching_files source_glob destination_dir)
  file(GLOB _matches "${source_glob}")
  foreach(_match IN LISTS _matches)
    get_filename_component(_name "${_match}" NAME)
    if(NOT EXISTS "${destination_dir}/${_name}")
      execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${_match}" "${destination_dir}/${_name}")
    endif()
  endforeach()
endfunction()

file(MAKE_DIRECTORY "${_lib_dir}" "${_pkgconfig_dir}" "${_include_dir}")

_link_matching_files("${_host_libdir}/libm.so*" "${_lib_dir}")

file(MAKE_DIRECTORY "${_include_dir}")
if(EXISTS "/usr/include/X11" AND NOT EXISTS "${_include_dir}/X11")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "/usr/include/X11" "${_include_dir}/X11")
endif()

_link_matching_files("${_host_libdir}/pkgconfig/x*.pc" "${_pkgconfig_dir}")
_link_matching_files("${_host_libdir}/pkgconfig/pthread-stubs.pc" "${_pkgconfig_dir}")
_link_matching_files("${_host_libdir}/pkgconfig/ice.pc" "${_pkgconfig_dir}")
_link_matching_files("${_host_libdir}/pkgconfig/sm.pc" "${_pkgconfig_dir}")
_link_matching_files("${_host_libdir}/pkgconfig/libdrm.pc" "${_pkgconfig_dir}")
_link_matching_files("/usr/share/pkgconfig/x*.pc" "${_pkgconfig_dir}")
_link_matching_files("/usr/share/pkgconfig/kbproto.pc" "${_pkgconfig_dir}")
_link_matching_files("/usr/share/pkgconfig/damageproto.pc" "${_pkgconfig_dir}")
_link_matching_files("/usr/share/pkgconfig/fixesproto.pc" "${_pkgconfig_dir}")
_link_matching_files("${_host_libdir}/libX11.so*" "${_lib_dir}")

if(KODI_DEPENDS_RENDER_SYSTEM STREQUAL "gl")
  if(EXISTS "/usr/include/GL" AND NOT EXISTS "${_include_dir}/GL")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "/usr/include/GL" "${_include_dir}/GL")
  endif()
  _link_matching_files("${_host_libdir}/pkgconfig/gl.pc" "${_pkgconfig_dir}")
  _link_matching_files("${_host_libdir}/pkgconfig/glu.pc" "${_pkgconfig_dir}")
  _link_matching_files("${_host_libdir}/libGL.so*" "${_lib_dir}")
else()
  message(STATUS "Skipping GL system links for non-GL render system: ${KODI_DEPENDS_RENDER_SYSTEM}")
endif()
