# Generic depends-driven toolchain template for CMake-native depends bootstrap.
# This file is intended as a stable replacement entrypoint for generated
# tools/depends Toolchain.cmake where possible.

set(DEPENDS_PATH "${DEPENDS_PATH}" CACHE PATH "Target depends prefix")
set(NATIVEPREFIX "${NATIVEPREFIX}" CACHE PATH "Native tools prefix")

if(NOT DEPENDS_PATH)
  message(FATAL_ERROR "DEPENDS_PATH must be set for KodiDependsToolchain.cmake")
endif()

if(NOT NATIVEPREFIX)
  message(FATAL_ERROR "NATIVEPREFIX must be set for KodiDependsToolchain.cmake")
endif()

if(NOT DEFINED KODI_DEPENDS_OS)
  set(KODI_DEPENDS_OS linux)
endif()
set(KODI_DEPENDS_OS "${KODI_DEPENDS_OS}" CACHE STRING "Depends target OS")
set(KODI_DEPENDS_CPU "${KODI_DEPENDS_CPU}" CACHE STRING "Depends target CPU")
set(KODI_DEPENDS_TARGET_PLATFORM "${KODI_DEPENDS_TARGET_PLATFORM}" CACHE STRING "Depends target platform")
set(KODI_DEPENDS_RENDER_SYSTEM "${KODI_DEPENDS_RENDER_SYSTEM}" CACHE STRING "Depends render system")

if(KODI_DEPENDS_OS STREQUAL "linux")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CORE_SYSTEM_NAME linux)
elseif(KODI_DEPENDS_OS STREQUAL "android")
  set(CMAKE_SYSTEM_NAME Android)
  set(CORE_SYSTEM_NAME android)
elseif(KODI_DEPENDS_OS STREQUAL "osx")
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME osx)
elseif(KODI_DEPENDS_OS STREQUAL "darwin_embedded")
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CORE_SYSTEM_NAME darwin_embedded)
elseif(KODI_DEPENDS_OS STREQUAL "wasm")
  set(CMAKE_SYSTEM_NAME Emscripten)
  set(CORE_SYSTEM_NAME wasm)
elseif(KODI_DEPENDS_OS STREQUAL "windows")
  set(CMAKE_SYSTEM_NAME Windows)
  set(CORE_SYSTEM_NAME windows)
elseif(KODI_DEPENDS_OS STREQUAL "freebsd")
  set(CMAKE_SYSTEM_NAME FreeBSD)
  set(CORE_SYSTEM_NAME freebsd)
endif()

set(KODI_DEPENDSBUILD 1)
if(KODI_DEPENDS_CPU AND NOT DEFINED CPU)
  set(CPU "${KODI_DEPENDS_CPU}" CACHE STRING "Target CPU from depends toolchain")
endif()
if(KODI_DEPENDS_TARGET_PLATFORM AND NOT DEFINED CORE_PLATFORM_NAME)
  set(CORE_PLATFORM_NAME "${KODI_DEPENDS_TARGET_PLATFORM}" CACHE STRING "Target platform from depends toolchain")
endif()
if(KODI_DEPENDS_RENDER_SYSTEM AND NOT DEFINED APP_RENDER_SYSTEM)
  set(APP_RENDER_SYSTEM "${KODI_DEPENDS_RENDER_SYSTEM}" CACHE STRING "Render system from depends toolchain")
endif()

set(CMAKE_FIND_ROOT_PATH "${DEPENDS_PATH}")
set(CMAKE_LIBRARY_PATH "${DEPENDS_PATH}/lib")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_FRAMEWORK LAST)

set(ENV{PKG_CONFIG_LIBDIR} "${DEPENDS_PATH}/lib/pkgconfig:${DEPENDS_PATH}/share/pkgconfig")
set(ENV{ACLOCAL_PATH} "${DEPENDS_PATH}/share/aclocal:${NATIVEPREFIX}/share/aclocal")
set(ENV{PATH} "${NATIVEPREFIX}/bin:$ENV{PATH}")
set(ENV{CMAKE_PREFIX_PATH} "${DEPENDS_PATH}")

find_file(CONFIG_SITE "config.site" PATHS "${DEPENDS_PATH}/share" NO_CMAKE_FIND_ROOT_PATH)
if(CONFIG_SITE)
  set(ENV{CONFIG_SITE} "${CONFIG_SITE}")
endif()

find_file(MESON_CROSS_FILE "cross-file.meson" PATHS "${DEPENDS_PATH}/share" NO_CMAKE_FIND_ROOT_PATH)
